version: '2'

services:
  medic:    
    container_name: medic
    image: medic
    build: .
    volumes:
      - .:/src
    networks:
      - main_network

  redis:
    container_name: medic_redis
    image: redis
    ports:
        - "6379"
    networks:
        - main_network

networks:
  main_network:
    driver: bridge
