version: '2'

services:
  medic:    
    container_name: medic
    image: medic
    build: .
    volumes:
      - .:/src
    networks:
      - main_network

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  redis:
    container_name: medic_redis
    image: redis
    ports:
        - "6379"
    networks:
        - main_network

networks:
  main_network:
    driver: bridge

volumes:
  mongodb_data_container:
